### ISSUE TITLE
 Connection failed! Trying again

### ISSUE THREAD

**Issue by aamirxs** [devgaganin/Save-Restricted-Content-Bot-V2#44]
INFO/2024-09-24 11:51:39,661] pyrogram.connection.connection: Connecting...
[WARNING/2024-09-24 11:51:49,666] pyrogram.connection.connection: Unable to connect due to network issues: Connection timed out
[ INFO/2024-09-24 11:51:50,668] pyrogram.connection.connection: Connecting...
[WARNING/2024-09-24 11:52:00,679] pyrogram.connection.connection: Unable to connect due to network issues: Connection timed out
[ INFO/2024-09-24 11:52:01,680] pyrogram.connection.connection: Connecting...
[WARNING/2024-09-24 11:52:11,691] pyrogram.connection.connection: Unable to connect due to network issues: Connection timed out
[WARNING/2024-09-24 11:52:12,692] pyrogram.connection.connection: Connection failed! Trying again...
[ INFO/2024-09-24 11:52:12,692] pyrogram.session.auth: Retrying due to ConnectionError: 
[ INFO/2024-09-24 11:52:12,692] pyrogram.connection.connection: Disconnected
[ INFO/2024-09-24 11:52:12,693] pyrogram.connection.connection: Disconnected
[ INFO/2024-09-24 11:52:12,693] pyrogram.session.session: Session stopped
Traceback (most recent call last):
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/methods/auth/sign_in_bot.py", line 51, in sign_in_bot
    r = await self.invoke(
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.see_other_303.UserMigrate: Telegram says: [303 USER_MIGRATE_X] - The user whose identity is being used to execute queries is associated with DC5 (for registration) (caused by "auth.ImportBotAuthorization")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/aamir/Desktop/New Folder/Save-Restricted-Content-Bot-V2/devgagan/__init__.py", line 45, in <module>
    loop.run_until_complete(restrict_bot())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/aamir/Desktop/New Folder/Save-Restricted-Content-Bot-V2/devgagan/__init__.py", line 35, in restrict_bot
    await app.start()
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 62, in start
    await self.authorize()
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/client.py", line 333, in authorize
    return await self.sign_in_bot(self.bot_token)
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/methods/auth/sign_in_bot.py", line 64, in sign_in_bot
    await Auth(
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/session/auth.py", line 274, in create
    raise e
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/session/auth.py", line 84, in create
    await self.connection.connect()
  File "/home/aamir/.local/lib/python3.10/site-packages/pyrogram/connection/connection.py", line 62, in connect
    raise ConnectionError
ConnectionError

**Comment by devgaganin** [comment]
DC5 token error use the deployment server accordingly
