### ISSUE TITLE
this time 

### ISSUE THREAD

**Issue by aamirxs** [devgaganin/Save-Restricted-Content-Bot-V2#54]
[ INFO/2024-10-17 13:21:54,911] pyrogram.dispatcher: Started 10 HandlerTasks
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/Save-Restricted-Content-Bot-V2/devgagan/__main__.py", line 30, in <module>
    loop.run_until_complete(devggn_boot())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/Save-Restricted-Content-Bot-V2/devgagan/__main__.py", line 20, in devggn_boot
    importlib.import_module("devgagan.modules." + all_module)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/Save-Restricted-Content-Bot-V2/devgagan/modules/main.py", line 8, in <module>
    from devgagan.core.get_func import get_msg
  File "/home/ubuntu/Save-Restricted-Content-Bot-V2/devgagan/core/get_func.py", line 357, in <module>
    SUPER_USERS = load_authorized_users()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Save-Restricted-Content-Bot-V2/devgagan/core/get_func.py", line 344, in load_authorized_users
    for user_doc in collection.find():
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/cursor.py", line 1281, in __next__
    return self.next()
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/cursor.py", line 1257, in next
    if len(self._data) or self._refresh():
                          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/cursor.py", line 1205, in _refresh
    self._send_message(q)
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/cursor.py", line 1100, in _send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/mongo_client.py", line 1754, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
    ).run()
      ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/mongo_client.py", line 2691, in _read
    with self._client._conn_from_server(self._read_pref, self._server, self._session) as (
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/mongo_client.py", line 1683, in _conn_from_server
    with self._checkout(server, session) as conn:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/mongo_client.py", line 1593, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/pool.py", line 1336, in checkout
    conn = self._get_conn(checkout_started_time, handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/pool.py", line 1495, in _get_conn
    conn = self.connect(handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/pool.py", line 1296, in connect
    conn.authenticate()
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/pool.py", line 648, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/auth.py", line 452, in authenticate
    auth_func(credentials, conn)
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/auth.py", line 356, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/auth.py", line 134, in _authenticate_scram
    res = conn.command(source, cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/helpers.py", line 45, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/pool.py", line 538, in command
    return command(
           ^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymongo/synchronous/network.py", line 218, in command
    helpers_shared._check_command_response(
  File "/usr/local/lib/python3.12/dist-packages/pymongo/helpers_shared.py", line 247, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'}
root@ip-172-31-4-221:/home/ubuntu/Save-Restricted-Content-Bot-V2#

**Comment by devgaganin** [comment]
Set mongo db network access settings to 0.0.0.0
